<a href="https://colab.research.google.com/github/saeedalig/NumPy-Tutorials/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Array

In [ ]:
import numpy as np

In [ ]:
x = [1,2,3,4,5]
y = np.array(x)
z = np.array([5,6,7])
print(z)
print(y)

print(type(y))

print(y.ndim)

[5 6 7]
[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [ ]:
two_dim = np.array([[1,2,3,4], [5,6,7,8]])
print(two_dim)
print('dimension is :',two_dim.ndim)

[[1 2 3 4]
 [5 6 7 8]]
dimension is : 2


In [ ]:
three_dim = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(three_dim)
print( 'dimension is :',three_dim.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is : 3


In [ ]:
multi_dim = np.array([1,2,3,4,5], ndmin = 5)
print(multi_dim)
print('dimension is :',multi_dim.ndim)

[[[[[1 2 3 4 5]]]]]
dimension is : 5


## Zeros

In [ ]:
zero_1 = np.zeros(4)
print(zero_1)
print()
print('dimension is :', zero_1.ndim)

print("-------------------------------------")

zero_2 = np.zeros((3,4))
print(zero_2)
print()
print('dimension is :', zero_2.ndim)

[0. 0. 0. 0.]

dimension is : 1
-------------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

dimension is : 2


## Ones

In [ ]:
one_1 = np.ones(4)
print(one_1)
print()
print('dimension is :',one_1.ndim)

print("---------------------------------")

one_2 = np.ones((3,4))
print(one_2)
print()
print('dimension is :',one_2.ndim)

[1. 1. 1. 1.]

dimension is : 1
---------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

dimension is : 2


##  Range Array

In [ ]:
ar_range = np.arange(4)
print(ar_range)
print(ar_range.ndim)

[0 1 2 3]
1


## Diagonal

In [ ]:
ar_diag = np.eye(3)
print(ar_diag)
print(ar_diag.ndim)

print("_________________________")


ar_diag1 = np.eye(3,4)
print(ar_diag1)
print(ar_diag1.ndim)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2
_________________________
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
2


## Linspace

In [ ]:
ar_lin = np.linspace(1,10, num=5)
print(ar_lin)
print(ar_lin.ndim)

[ 1.    3.25  5.5   7.75 10.  ]
1


In [ ]:
ar_lin = np.linspace(0,1, num=5)
print(ar_lin)
print(ar_lin.ndim)

[0.   0.25 0.5  0.75 1.  ]
1


## Random

##### Rand ( value btw 0 t0 1 )

In [ ]:
ar_rand = np.random.rand(5)             ## Only Positive Value
print(ar_rand)
print()
print(type(ar_rand))
print()
print('dimension is :',ar_rand.ndim)

[0.39890136 0.54103414 0.74458232 0.53191813 0.65259901]

<class 'numpy.ndarray'>

dimension is : 1


#### randn ( value close to 0 )

In [ ]:
ar_randn = np.random.randn(5,5)  ## value -> Positive & Negative
print(ar_randn)
print()
print(type(ar_randn))
print()
print('dimension is :',ar_randn.ndim)

[[ 0.37411376 -0.28806907 -0.28849754 -1.25265786 -0.0828253 ]
 [ 0.58815895  0.86951342  0.67119527 -1.27693361  0.59361851]
 [-1.02306061  0.39056554 -1.50797214 -0.87748993 -1.1073127 ]
 [ 0.61858615  0.99432206 -0.63338268  1.12488093  0.03832182]
 [-0.65914661  0.66316269 -0.24815538 -0.47698335 -1.25081183]]

<class 'numpy.ndarray'>

dimension is : 2


#### randint()

In [ ]:
rand_int = np.random.randint(5,15,5)      ## (min_no, max_no, total_no to be generated)
print(rand_int)
print(rand_int.ndim)

[10 11  7  7  6]
1


### Data Type

In [ ]:
data_type = np.array([1,2,3,5]) 
print(data_type)

print()

data_type1 = np.array([1,2,3,5], dtype = float) 
print(data_type1)

print()

data_type2 = np.array([1,2,3,5], dtype = str) 
print(data_type2)

print()

data_type3 = np.array([1., 2., 3., 5.], dtype = int)
print(data_type3)

[1 2 3 5]

[1. 2. 3. 5.]

['1' '2' '3' '5']

[1 2 3 5]


In [ ]:
data_type = np.array([1,2,3,5]) 

data_astype = data_type.astype(float)  ### changed into float

print(data_type)
print(data_astype)

[1 2 3 5]
[1. 2. 3. 5.]


## Shape & Reshape

In [ ]:
arr = np.array([[1,2],[1,2]])
print(arr)

print()
print('shape :',arr.shape)

print()
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

print()
print('shape :',arr1.shape)
print(arr1.ndim)

print()

var = np.array([1,2,3,4])
x = var.reshape(2,2)   ## reshaping one_dimensional array into 2D
print(x)
print('dimension :',x.ndim)

print()

y = x.reshape(-1)     ## reshaping 2D array into 1D
print(y)
print('dimension :',y.ndim)

[[1 2]
 [1 2]]

shape : (2, 2)

[[1 2 3 4]
 [5 6 7 8]]

shape : (2, 4)
2

[[1 2]
 [3 4]]
dimension : 2

[1 2 3 4]
dimension : 1


## Arithmetic Operation

In [ ]:
var = np.array([1,2,3,4])
var_add = var + 3
print(var_add)
print()

var = np.array([1,2,3,4])
var_sub = var - 3
print(var_sub)
print()

var = np.array([1,2,3,4])
var_divide = var / 3
print(var_divide)
print()

var = np.array([1,2,3,4])
var_multiply = var * 3
print(var_multiply)

[4 5 6 7]

[-2 -1  0  1]

[0.33333333 0.66666667 1.         1.33333333]

[ 3  6  9 12]


In [ ]:
var = np.array([1,2,3,4])
var1 = np.array([3,4,5,6])
new_var = var + var1
new_var1 = np.add(var, var1)   ### np.add  adds the variables

new_var2 = np.add(var, 3)

print(new_var)
print()

print(new_var1)

print()

print(new_var2)

[ 4  6  8 10]

[ 4  6  8 10]

[4 5 6 7]


In [ ]:
ar_min = np.array([6,4,8,3])

print("min :", np.min(ar_min))
print()

print("max :", np.max(ar_min))
print()

print("sqrt :", np.sqrt(ar_min))

min : 3

max : 8

sqrt : [2.44948974 2.         2.82842712 1.73205081]


In [ ]:
var1 = np.array([[8,9,7], [5,6,4]])   ## axis = 1 --> Row, axis = 0 --> Column

print(np.min(var1, axis = 0))
print(var1.ndim)


# print("max :", np.max(var1, axis = 0)





[5 6 4]
2


### Indexing 

In [ ]:
var =  np.array([6,4,8,3])
print(var)
print(var.ndim)

print()

print(var[2]) 
print(var[3])


[6 4 8 3]
1

8
3


var =  np.array([6,4,8,3)

In [ ]:
var1 = np.array([[8,9,7], [5,6,4]])   ## 2D
print(var1[0,2])
print()
print(var1[0,1])  ## 0 --> representing index no of [8,9,7]
print(var1[1,2])  ## 1 --> representing index no of [5,6,4]

7

9
4


## Slicing

In [ ]:
var =  np.array([6,4,8,3,8,6,8])

print(var[1:]) 
print(var[:1])
print(var[2:5])
print(var[:-1]) 
print(var[-4:-1]) 
print()

print(var[::2])  ## one element skipped
print()

print(var[1:6:3])    ## two element skipped


[4 8 3 8 6 8]
[6]
[8 3 8]
[6 4 8 3 8 6]
[3 8 6]

[6 8 8 8]

[4 8]


## Iteration

In [ ]:
var =  np.array([6,4,8,3,8,6,8])

for i in var:
    print(i)

6
4
8
3
8
6
8


In [ ]:
var1 = np.array([[8,9,7], [5,6,4]]) 

for j in var1:
    print(j)

print()

for k in var1:        ## for 2D you need tu use for loop two times , similarly for 3D three times
    for l in k:
        print(l)
        
print()

for i in np.nditer(var1):     ## np.ndinter() function produces same result (above example)
    print(i)

[8 9 7]
[5 6 4]

8
9
7
5
6
4

8
9
7
5
6
4


In [ ]:
x = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(x, flags = ['buffered'], op_dtypes = ['S']):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'


In [ ]:
var =  np.array([6,4,8,3,8,6,8])
for i,d in np.ndenumerate(var):     ## np.ndenumerate() gives index no. along with values
    print(i,d)

(0,) 6
(1,) 4
(2,) 8
(3,) 3
(4,) 8
(5,) 6
(6,) 8


In [ ]:
x = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i,d in np.ndenumerate(x):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9


## Copy vs View

In [ ]:
var =  np.array([6,4,8,3])
var_copy = var.copy()

var[1] = 40  ## no changes made in copy data when you modify original data.

print("var :", var)
print("copy :", var_copy)

var : [ 6 40  8  3]
copy : [6 4 8 3]


In [ ]:
var =  np.array([6,4,8,3])
var_copy = var.view()

var[1] = 40   ## changes made in view data when you modify original data.

print("var :", var)
print("view :", var_copy)

var : [ 6 40  8  3]
view : [ 6 40  8  3]


## Join Array

In [ ]:
x =  np.array([6,4,8,3])
y =  np.array([5,8,9,4])

concat_xy = np.concatenate((x,y))
print(concat_xy)

[6 4 8 3 5 8 9 4]


In [ ]:
x =  np.array([[6,4],[8,3]])
y =  np.array([[5,8],[9,4]])

concat_xy = np.concatenate((x,y), axis = 1)  ## joining along row (axis = 1)
print(concat_xy)

print("__________________")

concat_xy = np.concatenate((x,y), axis = 0)  ## joining along column (axis = 0)
print(concat_xy)

[[6 4 5 8]
 [8 3 9 4]]
__________________
[[6 4]
 [8 3]
 [5 8]
 [9 4]]


In [ ]:
x =  np.array([[6,4],[8,3]])           ## np.concatenate() == np.stack()
y =  np.array([[5,8],[9,4]])

concat_xy = np.vstack((x,y))     ## vstack--> joining vertically( Column),   dstack--> along height,   
concat_xy1 = np.hstack((x,y))     ## vstack--> joining horizentally (Row)
print(concat_xy)
print()
print(concat_xy1)

[[6 4]
 [8 3]
 [5 8]
 [9 4]]

[[6 4 5 8]
 [8 3 9 4]]


## Split Array

In [ ]:
var =  np.array([6,4,8,3,8,6,8])
x = np.array_split(var,3)  ### split into 3 arrays
print(x)

[array([6, 4, 8]), array([3, 8]), array([6, 8])]


In [ ]:
x =  np.array([[6,4],[8,3]])
y = np.array_split(x,4)
print(y)

print("----------------------------")

y1 = np.array_split(x,4, axis = 1) 
print(y1)

[array([[6, 4]]), array([[8, 3]]), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32)]
----------------------------
[array([[6],
       [8]]), array([[4],
       [3]]), array([], shape=(2, 0), dtype=int32), array([], shape=(2, 0), dtype=int32)]


## Search

In [ ]:
var =  np.array([6,4,8,3,8,6,8,3,5,6,8])
# index          0,1,2,3,4,5,6,7,8,9,10
x = np.where(var == 8)                  ## returns index no. of the value
print(x)

print()

x1 = np.where((var%2) == 0)                  ## returns index no. of the value
print(x1)

(array([ 2,  4,  6, 10], dtype=int64),)

(array([ 0,  1,  2,  4,  5,  6,  9, 10], dtype=int64),)


## sort()

In [ ]:
var =  np.array([2,4,8,3,10,6,5,0,6,9])   ## 1D

print(np.sort(var))

print()

var1 =  np.array([[2,4,8,3],[10,6,5,0],[8,5,6,9]])  ## 2D

print(np.sort(var1))

[ 0  2  3  4  5  6  6  8  9 10]

[[ 2  3  4  8]
 [ 0  5  6 10]
 [ 5  6  8  9]]


## Filter Array

In [ ]:
x =  np.array([6,4,8,3])
f = [True, False, True, False]
y = x[f]
print(y)      ## returns only True values

[6 8]


## Unique

In [ ]:
x = np.array([1,2,3,5,6,4,5,6,6,6])
y = np.unique(x, return_index=True, return_counts=True)
print(y)

(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 5, 3, 4], dtype=int64), array([1, 1, 1, 1, 2, 4], dtype=int64))


## Resize, Flatten, Ravel

In [ ]:
x =  np.array([6,4,8,3,6,9])
y = np.resize(y,(2,3))    ## converts 1D to 2D
print(y)

print()

print('flatten :',y.flatten(order = "F"))  ## flatten and ravel converts 2D array to 1D array
print()

print('ravel :',y.ravel(order = "F"))

[[1 2 3]
 [4 5 6]]

flatten : [1 4 2 5 3 6]

ravel : [1 4 2 5 3 6]


## Insert

In [ ]:
x =  np.array([6,4,8,3,6,9])
print(x)
print()

y = np.insert(x, 2,50)   ## at index 2(8) inserted 40
print(y)

print()

y1 = np.insert(x, (2,4) ,50)    ## at index 2 and 4(8,6) inserted 50
print(y1)

[6 4 8 3 6 9]

[ 6  4 50  8  3  6  9]

[ 6  4 50  8  3 50  6  9]


In [ ]:
x =  np.array([[6,4,8],[3,6,9]])
y = np.insert(x, 1,5, axis= 1)  ## 5,5 inserted in row at index 1
print(y)
print()

y1 = np.insert(x, 1,5, axis= 0)   ## 5,5,5 inserted in column at index 1
print(y1)

[[6 5 4 8]
 [3 5 6 9]]

[[6 4 8]
 [5 5 5]
 [3 6 9]]


## Delete

In [ ]:
x =  np.array([6,4,8,3,6,9])
d = np.delete(x, 2)   ## data deleted of index 2 that's 8
print(x)
print(d)

[6 4 8 3 6 9]
[6 4 3 6 9]


## Matrix

In [ ]:
x = np.matrix([[1,2], [1,2]])
x1 = np.matrix([[3,4], [3,4]])

print(x.dot(x1))          ## matrix - not multiplied like array(x*x1)

[[ 9 12]
 [ 9 12]]


In [ ]:
x = np.matrix([[1,2,3], [4,5,6]])
print(x)
print()

print(np.transpose(x))  ## transposed the index(order)
print()
print(x.T)              ## acts like np.transpose

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
x = np.matrix([[1,3], [4,2]])
print(x)
print()

print(np.swapaxes(x, 0 ,1))  ## row converted to column and coulmn to row

[[1 3]
 [4 2]]

[[1 4]
 [3 2]]


In [ ]:
x = np.matrix([[1,2], [3,4]])
print(x)
print()

print(np.linalg.inv(x))  ## inverse of matrix

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
x = np.matrix([[1,2], [3,4]])
print(x)
print()

print(np.linalg.matrix_power(x,0))  ## always return identity matrix
print()

print(np.linalg.matrix_power(x,2))
print()

print(np.linalg.matrix_power(x,-2))
                            

[[1 2]
 [3 4]]

[[1 0]
 [0 1]]

[[ 7 10]
 [15 22]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [ ]:
x = np.matrix([[1,2], [3,4]])
print(x)
print()

print(np.linalg.det(x))  ## determinate

[[1 2]
 [3 4]]

-2.0000000000000004
